/*******************************************************************************
* Copyright © 2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware, Inc.     *
* ALL RIGHTS RESERVED.                                                         *
*                        MapAware License v1.0                                 *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION  *
* OBTAINING A COPY OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE,  *
* DISPLAY, DISTRIBUTE, EXECUTE, AND TRANSMIT THE SOFTWARE, AND TO PREPARE      *
* DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD - PARTIES TO WHOM THE  *
* SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :               *
*                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING   *
* THE ABOVE LICENSE GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST *
* BE INCLUDED IN ALL COPIES OF THE SOFTWARE, IN WHOLE OR IN PART, AND ALL      *
* DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES OR DERIVATIVE WORKS ARE *
* SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY A SOURCE *
* LANGUAGE PROCESSOR.                                                          *
*                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   *
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     *
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON - INFRINGEMENT.IN NO EVENT   *
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    *
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  *
* DEALINGS IN THE SOFTWARE.                                                    *
*******************************************************************************/
/**
 * @file rdbtest.c
 * @brief libredisdb api test app
 *
 * @author mapaware@hotmail.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 0.0.4
 *
 * @since 2024-09-21 13:33:53
 * @date 2025-08-12 15:18:55
 *
 * @note
 *
 * @see https://github.com/redis/hiredis
 */
#include "redisdb_api.h"

#include <common/unitypes.h>

// 手工设置下面的值:
#define CLUSTER_ALL_NODES  "file:///opt/redis_cluster/radius/CLUSTER_ALL_NODES"
#define CLUSTER_AUTH_PASS  "file:///opt/redis_cluster/radius/CLUSTER_AUTH_PASS"

int main(int argc, char *argv[])
{
    RDBEnv env;
    RDBCtxNode node;

    printf("CLUSTER_ALL_NODES: %s\n", CLUSTER_ALL_NODES);
    printf("CLUSTER_AUTH_PASS: %s\n", CLUSTER_AUTH_PASS);

    env = RDBEnvCreate(CLUSTER_ALL_NODES, CLUSTER_AUTH_PASS);
    if (! env) {
        exit(-1);
    }

    int nodes = RDBEnvGetNodes(env);
    printf("all nodes=%d\n", nodes);

    node = RDBEnvGetNodeAt(env, 0);

    node = RDBEnvConnectNode(env, node, 0, 0);

    RDBEnvFree(env);
    return 0;
}