/*******************************************************************************
* Copyright © 2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware, Inc.     *
* ALL RIGHTS RESERVED.                                                         *
*                        MapAware License v1.0                                 *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION  *
* OBTAINING A COPY OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE,  *
* DISPLAY, DISTRIBUTE, EXECUTE, AND TRANSMIT THE SOFTWARE, AND TO PREPARE      *
* DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD - PARTIES TO WHOM THE  *
* SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :               *
*                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING   *
* THE ABOVE LICENSE GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST *
* BE INCLUDED IN ALL COPIES OF THE SOFTWARE, IN WHOLE OR IN PART, AND ALL      *
* DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES OR DERIVATIVE WORKS ARE *
* SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY A SOURCE *
* LANGUAGE PROCESSOR.                                                          *
*                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   *
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     *
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON - INFRINGEMENT.IN NO EVENT   *
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    *
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  *
* DEALINGS IN THE SOFTWARE.                                                    *
*******************************************************************************/
/**
 * @file redisdb_ctx.h
 * @brief libredisdb
 *
 * @author mapaware@hotmail.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 0.0.6
 *
 * @since 2024-09-21 13:33:53
 * @date 2025-08-12 15:20:19
 *
 * @note
 *
 * @see https://github.com/redis/hiredis
 */
#ifndef REDISDB_CTX_H_INCL
#define REDISDB_CTX_H_INCL

#if defined(__cplusplus)
extern "C" {
#endif

#include "redisdb_err.h"

#ifndef MAXPASSWORDLEN
#  define  MAXPASSWORDLEN  32
#endif


typedef struct _RedisdbCtxNode
{
    redisContext *ctx;

    int conn_timeo_ms;
    int io_timeo_ms;

    // 服务端口号
    int port;

    // 主机名. MAXHOSTNAMELEN 是此数组的大小，如果有空间，主机名以空字符结束
    char host[MAXHOSTNAMELEN];

    // 认证密码. MAXPASSWORDLEN 是此数组的大小，如果有空间，密码以空字符结束
    char auth[MAXPASSWORDLEN];
} RedisdbCtxNode;


void RDBCtxNodeFree(RedisdbCtxNode *ctxnode);



#if defined(__cplusplus)
}
#endif
#endif /* REDISDB_CTX_H_INCL */