/*******************************************************************************
* Copyright © 2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware, Inc.     *
* ALL RIGHTS RESERVED.                                                         *
*                        MapAware License v1.0                                 *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION  *
* OBTAINING A COPY OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE,  *
* DISPLAY, DISTRIBUTE, EXECUTE, AND TRANSMIT THE SOFTWARE, AND TO PREPARE      *
* DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD - PARTIES TO WHOM THE  *
* SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :               *
*                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING   *
* THE ABOVE LICENSE GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST *
* BE INCLUDED IN ALL COPIES OF THE SOFTWARE, IN WHOLE OR IN PART, AND ALL      *
* DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES OR DERIVATIVE WORKS ARE *
* SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY A SOURCE *
* LANGUAGE PROCESSOR.                                                          *
*                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   *
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     *
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON - INFRINGEMENT.IN NO EVENT   *
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    *
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  *
* DEALINGS IN THE SOFTWARE.                                                    *
*******************************************************************************/
/**
 * @file redisdb_api.h
 * @brief C api wrapper of hiredis to make redis apllication developing easier.
 *
 * @author mapaware@hotmail.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 0.0.3
 *
 * @since 2024-09-21 13:33:53
 * @date 2025-08-12 15:13:40
 *
 * @note
 *
 * @see https://github.com/redis/hiredis
 */
#ifndef REDISDB_API_H_PUBLIC
#define REDISDB_API_H_PUBLIC

#if defined(__cplusplus)
extern "C" {
#endif


#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>


#if defined(REDISDB_DLL)
/* win32 dynamic dll */
# ifdef REDISDB_EXPORTS
#   define REDISDB_API __declspec(dllexport)
# else
#   define REDISDB_API __declspec(dllimport)
# endif
#else
/* static lib or linux so */
# define REDISDB_API  extern
#endif

#define REDISDB_API_SUCCESS   (0)
#define REDISDB_API_ERROR    (-1)

#define REDISDB_API_NEXT      (1)

typedef struct _RedisdbEnv        * RDBEnv;
typedef struct _RedisdbCtxNode    * RDBCtxNode;

REDISDB_API const char * RDBLibVersion(void);

REDISDB_API void * RDBMemAlloc(size_t sizeb);

REDISDB_API void * RDBMemRealloc(void *old_addr, size_t old_sizeb, size_t new_sizeb);

REDISDB_API void RDBMemFree(void *addr);

/**
 * @brief Create RDBEnv Object
 *
 * @param cluster_nodes
 * @return A handle to RDBEnv Object
 */
REDISDB_API RDBEnv RDBEnvCreate(const char *cluster_nodes, const char *auth_pass);


/**
 * @brief
 *
 * @param env
 * @return REDISDB_API
 */
REDISDB_API void RDBEnvFree(RDBEnv env);

REDISDB_API int RDBEnvGetNodes(RDBEnv env);

REDISDB_API RDBCtxNode RDBEnvGetNodeAt(RDBEnv env, int index);

REDISDB_API RDBCtxNode RDBEnvConnectNode(RDBEnv env, RDBCtxNode node, int connect_timeout_ms, int io_timeout_ms);

REDISDB_API int RDBEnvDisconnectNode(RDBEnv env, RDBCtxNode node);

#if defined(__cplusplus)
}
#endif
#endif /* REDISDB_API_H_PUBLIC */