/*******************************************************************************
* Copyright © 2024-2025 Light Zhang <mapaware@hotmail.com>, MapAware, Inc.     *
* ALL RIGHTS RESERVED.                                                         *
*                        MapAware License v1.0                                 *
* PERMISSION IS HEREBY GRANTED, FREE OF CHARGE, TO ANY PERSON OR ORGANIZATION  *
* OBTAINING A COPY OF THE SOFTWARE COVERED BY THIS LICENSE TO USE, REPRODUCE,  *
* DISPLAY, DISTRIBUTE, EXECUTE, AND TRANSMIT THE SOFTWARE, AND TO PREPARE      *
* DERIVATIVE WORKS OF THE SOFTWARE, AND TO PERMIT THIRD - PARTIES TO WHOM THE  *
* SOFTWARE IS FURNISHED TO DO SO, ALL SUBJECT TO THE FOLLOWING :               *
*                                                                              *
* THE COPYRIGHT NOTICES IN THE SOFTWARE AND THIS ENTIRE STATEMENT, INCLUDING   *
* THE ABOVE LICENSE GRANT, THIS RESTRICTION AND THE FOLLOWING DISCLAIMER, MUST *
* BE INCLUDED IN ALL COPIES OF THE SOFTWARE, IN WHOLE OR IN PART, AND ALL      *
* DERIVATIVE WORKS OF THE SOFTWARE, UNLESS SUCH COPIES OR DERIVATIVE WORKS ARE *
* SOLELY IN THE FORM OF MACHINE - EXECUTABLE OBJECT CODE GENERATED BY A SOURCE *
* LANGUAGE PROCESSOR.                                                          *
*                                                                              *
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   *
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     *
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON - INFRINGEMENT.IN NO EVENT   *
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    *
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  *
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  *
* DEALINGS IN THE SOFTWARE.                                                    *
*******************************************************************************/
/**
 * @file redisdb_api.c
 * @brief C api wrapper of hiredis to make redis apllication developing easier.
 *
 * @author mapaware@hotmail.com
 * @copyright © 2024-2025 mapaware.top All Rights Reserved.
 * @version 0.0.3
 *
 * @since 2024-09-21 13:33:53
 * @date 2025-08-12 15:14:38
 *
 * @note
 *
 * @see https://github.com/redis/hiredis
 */
#include "redisdb_api.h"
#include "redisdb_env.h"

const char * RDBLibVersion(void)
{
    return "libredisdb-0.0.1";
}


void * RDBMemAlloc(size_t sizeb)
{
    return mem_alloc_zero(1, sizeb);
}


void * RDBMemRealloc(void *old_addr, size_t old_sizeb, size_t new_sizeb)
{
    void *new_addr = mem_realloc(old_addr, new_sizeb);

    if (old_sizeb != (size_t)(-1) && new_sizeb > old_sizeb) {
        bzero((char*)new_addr + old_sizeb, new_sizeb - old_sizeb);
    }

    return new_addr;
}


void RDBMemFree(void *addr)
{
    mem_free(addr);
}